###################################################################################
# Eduardo Acuña Yeomans 2015																										  #
# 																																							  #
# Este archivo permite la compilación de `simple_scanner.c` con el comando `make` #
###################################################################################

# Flags para el compilador: Mostrar todas las warnings e incluir la información de depuración
CFLAGS=-Wall -g

all: simple_scanner

clean:
	rm -f simple_scanner
